const express = require('express');
const app = express();
const sql = require('mssql');
const { config } = require('./sqlconfig');
const nodemailer = require('nodemailer');
const userRouter = require('./routes/userRoutes');
const scheduleSendMail = require('./services/sendMailJob');

require('dotenv').config();

app.use(express.urlencoded({ extended: true }));
app.use(express.json());


// cron jobb
scheduleSendMail(`Hello,
this email was autogenerated, 
it was scheduled to be send at 9:30 AM,

regards Kori;
`, 'jonathan.mwaniki@thejitu.com')

scheduleSendMail(`Hello,
this email was autogenerated, 
it was scheduled to be send at 9:30 AM,

regards Kori;
`, 'korijunior106@gmail.com')

// home route
app.get('/', (req, res) => {
    res.send({ message: "Welcome G" })
});

app.use('/users', userRouter)


const transporter = nodemailer.createTransport({
    host: 'smtp.gmail.com',
    port: 587,
    secure: false,
    requireTLS: true,
    auth: {
        user: 'standrewswomengroup@gmail.com',
        pass: 'edinqmqllshvowss'
        // user: 'korinjoroge63@gmail.com',
        // pass: 'kyfbyyavzjfjlmii'
    }
});

// app.get('/sendmail', (req, res) => {
//     console.log("send mail route")
//     const mailOptions = {
//         from: 'standrewswomengroup@gmail.com',
//         to: `korinjoroge63@gmail.com`,
//         subject: 'Registration!',
//         text: `Hello,Kori 
//         Your Registration was successful,
//         welcome.
//         Thank you `
//     };

// transporter.sendMail(mailOptions, function(error, info){
//     console.log("we sending")
//     if (error) {
//         res.send(error)
//         console.log(error);
//     } else {
//         res.json({message: 'Email sent successfully'})
//         console.log('Email sent: ' + info.response);
//     }
// });
// });







const port = process.env.PORT || 5555;
app.listen(port, () => { console.log(`Server listening too port ${port}`) })